return function(colors)
    return {
        CmpCompNormal = { bg = colors.black },
        CmpCompBorder = { fg = colors.grey },
        CmpDocNormal = { bg = colors.black },
        CmpDocBorder = { fg = colors.grey },
        CmpItemAbbr = { fg = colors.white },
        CmpItemAbbrMatch = { fg = colors.blue, bold = true },
        CmpItemKindConstant = { fg = colors.base09 },
        CmpItemKindFunction = { fg = colors.base0D },
        CmpItemKindIdentifier = { fg = colors.base08 },
        CmpItemKindField = { fg = colors.base08 },
        CmpItemKindVariable = { fg = colors.base0E },
        CmpItemKindSnippet = { fg = colors.red },
        CmpItemKindText = { fg = colors.base0B },
        CmpItemKindStructure = { fg = colors.base0E },
        CmpItemKindType = { fg = colors.base0A },
        CmpItemKindKeyword = { fg = colors.base07 },
        CmpItemKindMethod = { fg = colors.base0D },
        CmpItemKindConstructor = { fg = colors.blue },
        CmpItemKindFolder = { fg = colors.base07 },
        CmpItemKindModule = { fg = colors.base0A },
        CmpItemKindProperty = { fg = colors.base08 },
        -- CmpItemKindEnum = { fg = "" },
        CmpItemKindUnit = { fg = colors.base0E },
        -- CmpItemKindClass = { fg = "" },
        CmpItemKindFile = { fg = colors.base07 },
        -- CmpItemKindInterface = { fg = "" },
        CmpItemKindColor = { fg = colors.red },
        CmpItemKindReference = { fg = colors.base05 },
        -- CmpItemKindEnumMember = { fg = "" },
        CmpItemKindStruct = { fg = colors.base0E },
        -- CmpItemKindValue = { fg = "" },
        -- CmpItemKindEvent = { fg = "" },
        CmpItemKindOperator = { fg = colors.base05 },
        CmpItemKindTypeParameter = { fg = colors.base08 },
    }
end
